version: '3'

services:
  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no
    
    command: redis-server --appendonly yes

    ports:
    -  "6379:6379"